#!/bin/bash

#if ! [ -e /etc/apt/preferences.d/mozillateamppa ]; then
  echo "=萌え版でないfirefoxを消して、萌版のfirefoxを入れます="
  echo " ランチャのドックからfirefoxのお気に入りを一旦消します。"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp |  sed -e "s/'firefox.desktop', //g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"  
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp | sed -e "s/'firefox_firefox.desktop', //g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"
  #snap list contain firefox?
  if snap list | grep -q -n firefox; then
    echo " 萌え版でないfirefoxを消します"
    echo "  注意!!:firefoxを動かしながらは消せません。また、長い時間待たされてしまって表示が変わらない場合は、そもそものアップデートが終わっていないことがありますので、Ctrl-Cボタンを押してこのスクリプトを止めたあとに、ソフトウェアの更新でアップデートを先に済ましてください。"
    sudo snap remove --purge firefox
    sudo apt remove -y --autoremove firefox >/dev/null 2>/dev/null
  fi
  echo " 萌え版firefoxのリポジトリ（入手場所）を設定します。"
  sudo add-apt-repository -y ppa:mozillateam/ppa >/dev/null 2>/dev/null
  echo " 次回以降のアップデートでも、萌え版がアップデートされるように設定します。"
  sudo cp mozillateamppa /etc/apt/preferences.d/
  echo " 萌え版のfirefoxをインストールしています。（時間がかかることがあります。）"
  sudo apt update >/dev/null 2>/dev/null
  sudo apt -y install firefox
  echo " 萌え版のfirefoxをランチャのドックにお気に入りとして登録します。"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp | sed s/\\\\[/"['firefox.desktop',"/`
  gsettings set org.gnome.shell favorite-apps "$tmp"
  echo " 次回からのアップレート候補をお確かめください。"
  apt-cache policy firefox
  echo ""
  echo -n "キーを押してメニューに戻る:"
  read -r -n 1 -s answer
  echo ""
#fi

