#!/bin/bash

#if ! [ -e /etc/apt/preferences.d/mozillateamppa ]; then
  echo "=もとのsnap版のfirefoxを消してdeb版の可愛くできるfirefoxを入れます="
  echo " まず、お気に入りの毒気のアイコンを調整します"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp |  sed -e "s/'firefox.desktop', //g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"  
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp | sed -e "s/'firefox_firefox.desktop', //g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"
  #snap list contain firefox?
  if snap list | grep -q -n firefox; then
    echo " snap版のfirefoxを取り除きます"
    echo "  注意!!:もし消しているコマンドの状態が長く続きすぎた場合は、ハングアップしていることがあるので、Ctrl-Cでこのウインドウを閉じでアップデートをしてすべてのSnapをアップデートしてください!!"
    sudo snap remove --purge firefox
    sudo apt remove -y --autoremove firefox >/dev/null 2>/dev/null
  fi
  echo " deb版firefoxのリポジトリを足しこみます"
  sudo add-apt-repository -y ppa:mozillateam/ppa >/dev/null 2>/dev/null
  echo " 自動でアップデートしたときも、きちんとこのFirefoxがアップデートするようにしています"
  sudo cp mozillateamppa /etc/apt/preferences.d/
  echo " 実際にDEB版のfirefoxをインストールします"
  sudo apt update >/dev/null 2>/dev/null
  sudo apt -y install firefox
  echo " ドックのお気に入りにDEB版のfirefoxのアイコンを入れます"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp | sed s/\\\\[/"['firefox.desktop',"/`
  gsettings set org.gnome.shell favorite-apps "$tmp"
  echo " アップデート時の動作確認"
  apt-cache policy firefox
  echo ""
  echo -n "なにかキーを押してください:"
  read -r -n 1 -s answer
  echo ""
#fi

