#!/bin/bash

#if [ -e /etc/apt/preferences.d/mozillateamppa ]; then
  echo "=DEB版のfirefoxを消して、もとのsnap版のfirefoxを入れます=" 
  echo " お気に入りのドックアイコンからfirefoxアイコンを消します"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp |  sed -e "s/'firefox.desktop', //g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"  
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp | sed -e "s/'firefox_firefox.desktop', //g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"  
  echo " DEB版のfirefoxのアップデート用の動きを消します"
  sudo rm -rf /etc/apt/preferences.d/mozillateamppa
  echo " 実際にDEB版のFirefoxを消します"
  sudo apt remove --autoremove -y firefox >/dev/null 2>/dev/null
  echo " DEB版のfirefoxのリポジトリを消します"
  sudo add-apt-repository --remove -y ppa:mozillateam/ppa >/dev/null 2>/dev/null
  echo " snap版のfirefox（元のfirefox）を入れます"
  sudo snap install firefox
  echo " ドックにお気に入りを追加します"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp | sed s/\\\\[/"['firefox_firefox.desktop', "/`
  gsettings set org.gnome.shell favorite-apps "$tmp"
  echo ""
  echo -n "なにかキーを押してください:"
  read -r -n 1 -s answer
  echo ""
#fi

