#!/bin/bash
#==== MoeIcon variable ====
MoeIconUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/icons/MoePinkIcons_201117.tar.xz"
MoeIconFileName=`echo $MoeIconUrl|awk -F"/" '{print $NF}'`
MoeIconDirName=`echo $MoeIconFileName|awk '{print substr($0,0,index($0,"_")-1)}'`
MoeIconName=$MoeIconDirName
SYSIconDir="/usr/share/icons"
DefaultIconName="Yaru"
TempDir="Moebuntu.temp"

# Install curl
InstallCurl() {
  echo "=下準備でcurlというネットからのダウンロード用のコマンドをインストールする。="
  dpkg -s curl >/dev/null 2>&1
  if [ ! $? -eq 0 ]; then
    sudo apt install -y curl
    echo "終了"
    echo ""
    else
        echo "すでにインストールされていました。"
  fi
  echo ""
}

# main
# make temp directory
if [ ! -d $TempDir ]; then
  echo "=$TempDirという、一時フォルダを作ります="
  mkdir $TempDir
fi

# install or remove?
if [ "$1" = "install" ]; then
  # install
  echo "=$MoeIconFileNameをインストールします。="
  InstallCurl;
  echo " $MoeIconFileNameをダウンロードします。"
  curl -L $MoeIconUrl --output "$TempDir/$MoeIconFileName"
  echo " $MoeIconFileNameを展開します"
  tar Jxfv "$TempDir/$MoeIconFileName" -C $TempDir > /dev/null 2> /dev/null
  echo " $SYSIconDir　フォルダへコピーします。"
  sudo cp -R "$TempDir/$MoeIconDirName" "$SYSIconDir"
  echo " $MoeIconNameをシステムに設定します。"
  gsettings set org.gnome.desktop.interface icon-theme "$MoeIconName"
  echo "終了"
  # remove
  elif [ "$1" = "remove" ]; then
    echo "=$MoeIconFileNameを消して、既定のアイコンに戻します。 ="
    echo " $DefaultIconNameをシステムに設定します。"
    gsettings set org.gnome.desktop.interface icon-theme "$DefaultIconName"
    # if exsist remove MoeBuntuIcon
    if [ -d "$SYSIconDir/$MoeIconDirName" ]; then
      echo " $SYSIconDir/$MoeIconDirNameを消します。"
      sudo rm -rf "$SYSIconDir/$MoeIconDirName"
    fi
    echo "終了"
    echo ""
  else
    echo "install? remove?"
fi

echo "=$TempDirという一時フォルダーを消します。="
rm -rf $TempDir

echo ""
echo -n "キーを押してメニューに戻る:"
read -r -n 1 -s answer
