#!/bin/bash
#==== MoeIcon variable ====
MoeIconUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/icons/MoePinkIcons_201117.tar.xz"
MoeIconFileName=`echo $MoeIconUrl|awk -F"/" '{print $NF}'`
MoeIconDirName=`echo $MoeIconFileName|awk '{print substr($0,0,index($0,"_")-1)}'`
MoeIconName=$MoeIconDirName
SYSIconDir="/usr/share/icons"
DefaultIconName="Yaru"
TempDir="Moebuntu.temp"

# Install curl
InstallCurl() {
  echo "=curlをインストール="
  dpkg -s curl >/dev/null 2>&1
  if [ ! $? -eq 0 ]; then
    sudo apt install -y curl
    echo "完了"
    echo ""
    else
        echo "すでにインストールされていました。"
  fi
  echo ""
}

# main
# make temp directory
if [ ! -d $TempDir ]; then
  echo "=一時的なフォルダ $TempDir を作成します="
  mkdir $TempDir
fi

# install or remove?
if [ "$1" = "install" ]; then
  # install
  echo "=$MoeIconFileName をインストールします="
  InstallCurl;
  echo " $MoeIconFileName をダンロードします"
  curl -L $MoeIconUrl --output "$TempDir/$MoeIconFileName"
  echo " $MoeIconFileName 解凍"
  tar Jxfv "$TempDir/$MoeIconFileName" -C $TempDir > /dev/null 2> /dev/null
  echo " $SYSIconDir へコピー"
  sudo cp -R "$TempDir/$MoeIconDirName" "$SYSIconDir"
  echo " 今、存在している Moe*は次の通り:`ls -d /usr/share/icons/Moe*`"
  echo " $MoeIconName をセット中"
  gsettings set org.gnome.desktop.interface icon-theme "$MoeIconName"
  echo "完了"
  # remove
  elif [ "$1" = "remove" ]; then
    echo "=$MoeIconFileName を消して、元の状態に戻します"
    echo " seting to $DefaultIconName"
    gsettings set org.gnome.desktop.interface icon-theme "$DefaultIconName"
    # if exsist remove MoeBuntuIcon
    if [ -d "$SYSIconDir/$MoeIconDirName" ]; then
      echo " $SYSIconDir/$MoeIconDirName を消します"
      sudo rm -rf "$SYSIconDir/$MoeIconDirName"
    fi
    echo "完了"
    echo ""
  else
    echo "入れるの? 消すの?"
fi

echo "=一時的に使用した $TempDir を消します="
rm -rf $TempDir

echo ""
echo -n "なにかキーを押してください:"
read -r -n 1 -s answer
