#!/bin/bash

extman(){
    echo "1.上の「探す」タブを押して、\"User Themes\"を探してください。 "
    echo "2.そこの「追加」ボタンを押して、インストールしてください。"
    echo "3.上の「追加済み」タブを押して、その右のスイッチを「オン」にしてください。（右にスライドでオンです）"
    echo "　もし、上にスイッチばない場合は、 \"use extention\"のスイッチを「オン」にしてください。"
    echo "4.\"User Themes\"の右にあるスイッチを「オン」にしてください。"
extension-manager 2> /dev/null
}

# Main
echo "gnome-shell-managerをインストールします。"
dpkg -s gnome-shell-extension-manager >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt -y install gnome-shell-extension-manager
  echo "終了"
  echo ""
  else
      echo "すでにインストールされていました。"
fi
echo "--以下の手順で、今出できたWindowをセットしてください。--"
extman;
echo "ありがとうございます。"
echo " 「user-theme」というシステム設定項目を有効化します"
sudo cp ~/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/schemas/org.gnome.shell.extensions.user-theme.gschema.xml /usr/share/glib-2.0/schemas && sudo glib-compile-schemas /usr/share/glib-2.0/schemas
echo ""
echo -n "キーを押してメニューに戻る:"
read -r -n 1 -s answer
echo ""

