#!/bin/bash
# ====== COLORS ======
COL_BLACK="\x1b[30;01m"
COL_RED="\x1b[31;01m"
COL_GREEN="\x1b[32;01m"
COL_YELLOW="\x1b[33;01m"
COL_MAGENTA="\x1b[35;01m"
COL_CYAN="\x1b[36;01m"
COL_WHITE="\x1b[37;01m"
COL_BLUE="\x1b[34;01m"
COL_RESET="\x1b[39;49;00m"
# ====== theme urls ======
ThemePink="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/Moe-Pink16.tar.xz"
ThemeBlue="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/Moe-Blue16.tar.xz"
ThemeGreen="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/Moe-Green16.tar.xz"
ThemeBlueGreen="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/Moe-BlueGreen16.tar.xz"
ThemeNavy="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/Moe-Navy16.tar.xz"
ThemeOrange="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/Moe-Orange16.tar.xz"
ThemePurple="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/Moe-Purple16.tar.xz"
ThemeRed="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/Moe-Red16.tar.xz"
ThemeYellow="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/Moe-Yellow16.tar.xz"
# ====== login default picture(png) URL ======
LoginDefaltPicture="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/login-default.png"
# ====== Sound URL ======
Soundiori="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/sound/Moesound_iori.tar.gz"
Soundmaid_iori="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/sound/Moesound_maid_iori.tar.gz"
SoundSF_iori="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/sound/Moesound_SF_iori.tar.gz"
SoundMGd="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/sound/Moesound_MGd.tar.gz"

menu() {
clear
echo -e $COL_GREEN" ------------------------------------------------------------------------------"
echo -e "$COL_GREEN                          Moebuntu セッティング　ヘルパー　２"
echo -e $COL_GREEN" ------------------------------------------------------------------------------"$COL_RESET
PS3='選択肢を選んでね: '
options=( '基礎の設定(最初にやること)'
          'ピンクのテーマ'
          '青のテーマ'
          '緑のテーマ'
          '青緑のテーマ'
          'ネイビーのテーマ'
          'オレンジのテーマ'
          '紫のテーマ'
          '赤のテーマ'
          '黄のテーマ'
          '萌えテーマを消す'
          '萌えアイコン'
          '萌えアイコンを消す'
          '萌え起動画面'
          '萌起動画面を消す'
          '萌え壁紙'
          '萌え壁紙を消す'
          'firefoxを萌え版にする'
          'firefoxを萌えない版に戻す'
          '基本の萌え音'
          'メイド風萌え音'
          'SF風萌え音'
          '初音ミク萌え音'
          '萌え音を消す'
          '終了')

select opt in "${options[@]}"
do
  case $opt in
    "基礎の設定(最初にやること)")
      /bin/bash install-GSM;
      break
    ;;
    "ピンクのテーマ")
      /bin/bash set-theme $ThemePink $LoginDefaltPicture ;
      break
    ;;
    "青のテーマ")
      /bin/bash set-theme $ThemeBlue $LoginDefaltPicture;
      break
    ;;
    "緑のテーマ")
      /bin/bash set-theme $ThemeGreen $LoginDefaltPicture;
      break
    ;;
    "青緑のテーマ")
      /bin/bash set-theme $ThemeBlueGreen $LoginDefaltPicture;
      break
    ;;
    "ネイビーのテーマ")
      /bin/bash set-theme $ThemeNavy $LoginDefaltPicture;
      break
    ;;
    "オレンジのテーマ")
      /bin/bash set-theme $ThemeOrange $LoginDefaltPicture;
      break
    ;;
    "紫のテーマ")
      /bin/bash set-theme $ThemePurple $LoginDefaltPicture;
      break
    ;;
    "黄のテーマ")
      /bin/bash set-theme $ThemeYellow $LoginDefaltPicture;
      break
    ;;
    "赤のテーマ")
      /bin/bash set-theme $ThemeRed $LoginDefaltPicture;
      break
    ;;
    "萌えテーマを消す")
      /bin/bash theme2defalt ;
      break
    ;;
    "萌えアイコン")
      /bin/bash iconmanager install ;
      break
    ;;
    "萌えアイコンを消す")
      /bin/bash iconmanager remove ;
      break
    ;;
    "萌え起動画面")
      /bin/bash set-plymouth ;
      break
    ;;
    "萌起動画面を消す")
      /bin/bash plymouth2default ;
      break
    ;;
    "萌え壁紙")
      /bin/bash wallmanager install ;
      break
    ;;
    "萌え壁紙を消す")
      /bin/bash wallmanager remove ;
      break
    ;;
    "firefoxを萌え版にする")
      /bin/bash firefox2deb ;
      break
    ;;
    "firefoxを萌えない版に戻す")
      /bin/bash firefox2snap ;
      break
    ;;
    "基本の萌え音")
      /bin/bash setsound $Soundiori ;
      /bin/bash loginsound install ;
      break
    ;;
    "メイド風萌え音")
      /bin/bash setsound $Soundmaid_iori ;
      /bin/bash loginsound install ;
      break
    ;;
    "SF風萌え音")
      /bin/bash setsound $SoundSF_iori ;
      /bin/bash loginsound install ;
      break
    ;;
    "初音ミク萌え音")
      /bin/bash setsound $SoundMGd ;
      /bin/bash loginsound install ;
      break
    ;;
    "萌え音を消す")
      /bin/bash removesound ;
      /bin/bash loginsound remove ;
      break
    ;;
    "終了")
      exit 0
    ;;
    *)
      echo "invalid option $REPLY"
      break
    ;;
  esac
done
menu
}

## main
menu

