#!/bin/bash
# ====== COLORS ======
COL_BLACK="\x1b[30;01m"
COL_RED="\x1b[31;01m"
COL_GREEN="\x1b[32;01m"
COL_YELLOW="\x1b[33;01m"
COL_MAGENTA="\x1b[35;01m"
COL_CYAN="\x1b[36;01m"
COL_WHITE="\x1b[37;01m"
COL_BLUE="\x1b[34;01m"
COL_RESET="\x1b[39;49;00m"
# ====== theme urls ======
ThemePink="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/Moe-Pink17.tar.xz"
ThemeBlue="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/Moe-Blue17.tar.xz"
ThemeGreen="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/Moe-Green17.tar.xz"
ThemeBlueGreen="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/Moe-BlueGreen17.tar.xz"
ThemeNavy="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/Moe-Navy17.tar.xz"
ThemeOrange="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/Moe-Orange17.tar.xz"
ThemePurple="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/Moe-Purple17.tar.xz"
ThemeRed="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/Moe-Red17.tar.xz"
ThemeYellow="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/Moe-Yellow17.tar.xz"
# ====== login default picture(png) URL ======
LoginDefaltPicture="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/login-default.png"
# ====== Sound URL ======
Soundiori="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/sound/Moesound_iori.tar.gz"
Soundmaid_iori="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/sound/Moesound_maid_iori.tar.gz"
SoundSF_iori="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/sound/Moesound_SF_iori.tar.gz"
SoundMGd="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/sound/Moesound_MGd.tar.gz"

menu() {
clear
echo -e $COL_GREEN" --------------------------------------------------------------------------"
echo -e "$COL_GREEN                 Moebuntu 簡単セットアップ Ubntu24.04Lts対応版"
echo -e $COL_GREEN" --------------------------------------------------------------------------"$COL_RESET
PS3='行こなうメニューの番号: '
options=( '基本の設定(最初にする)'
          'ピンクのテーマ'
          '青のテーマ'
          '緑のテーマ'
          '青緑のテーマ'
          'ネイビーのテーマ'
          'オレンジのテーマ'
          '紫のテーマ'
          '赤のテーマ'
          '黄のテーマ'
          'テーマ削除'
          'かわいいアイコンセット'
          'アイコンもとに戻す'
          '起動待ち画面を可愛く設定'
          '起動待ち画面を戻す'
          'デスクトップの背景を変える'
          'デスクトップの背景をもとに戻す'
          'firefoxかわいくする'
          'firefox元に戻す'
          'ファイラーnemoを入れる'
          'ファイラーnemoをやめる'
          'ファイラーthunar入れる'
          'ファイラーthunarやめる'
          '動画再生vlcを入れる'
          '動画再生vlcをやめる'
          'サウンドMoesound_iori入れる'
          'サウンドMoesound_maid_iori入れる'
          'サウンドMoesound_SF_iori入れる'
          'サウンドMoesound_MGd入れる'
          'サウンドをやめる'
          'このソフトを終わる')

select opt in "${options[@]}"
do
  case $opt in
    "基本の設定(最初にする)")
      /bin/bash install-GSM;
      break
    ;;
    "ピンクのテーマ")
      /bin/bash set-theme $ThemePink $LoginDefaltPicture ;
      break
    ;;
    "青のテーマ")
      /bin/bash set-theme $ThemeBlue $LoginDefaltPicture;
      break
    ;;
    "緑のテーマ")
      /bin/bash set-theme $ThemeGreen $LoginDefaltPicture;
      break
    ;;
    "青緑のテーマ")
      /bin/bash set-theme $ThemeBlueGreen $LoginDefaltPicture;
      break
    ;;
    "ネイビーのテーマ")
      /bin/bash set-theme $ThemeNavy $LoginDefaltPicture;
      break
    ;;
    "オレンジのテーマ")
      /bin/bash set-theme $ThemeOrange $LoginDefaltPicture;
      break
    ;;
    "紫のテーマ")
      /bin/bash set-theme $ThemePurple $LoginDefaltPicture;
      break
    ;;
    "黄のテーマ")
      /bin/bash set-theme $ThemeYellow $LoginDefaltPicture;
      break
    ;;
    "赤のテーマ")
      /bin/bash set-theme $ThemeRed $LoginDefaltPicture;
      break
    ;;
    "テーマ削除")
      /bin/bash theme2defalt ;
      break
    ;;
    "かわいいアイコンセット")
      /bin/bash iconmanager install ;
      break
    ;;
    "アイコンもとに戻す")
      /bin/bash iconmanager remove ;
      break
    ;;
    "起動待ち画面を可愛く設定")
      /bin/bash set-plymouth ;
      break
    ;;
    "起動待ち画面を戻す")
      /bin/bash plymouth2default ;
      break
    ;;
    "デスクトップの背景を変える")
      /bin/bash wallmanager install ;
      break
    ;;
    "デスクトップの背景をもとに戻す")
      /bin/bash wallmanager remove ;
      break
    ;;
    "firefoxかわいくする")
      /bin/bash firefox2deb ;
      break
    ;;
    "firefox元に戻す")
      /bin/bash firefox2snap ;
      break
    ;;
    "ファイラーnemoを入れる")
      /bin/bash addnemo;
      break
    ;;
    "ファイラーnemoをやめる")
      /bin/bash removenemo ;
      break
    ;;
    "ファイラーthunar入れる")
      /bin/bash addthunar;
      break
    ;;
    "ファイラーthunarをやめる")
      /bin/bash removethunar ;
      break
    ;;
    "動画再生vlcを入れる")
      /bin/bash addvlc;
      break
    ;;
    "動画再生vlcをやめる")
      /bin/bash removevlc ;
      break
    ;;
    "サウンドMoesound_iori入れる")
      /bin/bash setsound $Soundiori ;
      /bin/bash loginsound install ;
      break
    ;;
    "サウンドMoesound_maid_iori入れる")
      /bin/bash setsound $Soundmaid_iori ;
      /bin/bash loginsound install ;
      break
    ;;
    "サウンドMoesound_SF_iori入れる")
      /bin/bash setsound $SoundSF_iori ;
      /bin/bash loginsound install ;
      break
    ;;
    "サウンドMoesound_MGd入れる")
      /bin/bash setsound $SoundMGd ;
      /bin/bash loginsound install ;
      break
    ;;
    "サウンドをやめる")
      /bin/bash removesound ;
      /bin/bash loginsound remove ;
      break
    ;;
    "このソフトを終わる")
      exit 0
    ;;
    *)
      echo "invalid option $REPLY"
      break
    ;;
  esac
done
menu
}

## main
menu

