#!/bin/bash

# main
# remove all Moesound
echo " すべてのかわいいサウンドを消します"
sudo rm -rf /usr/share/sounds/Moe*
# change sound gsetting
echo " gsettingsをYaruデフォルトに戻します"
gsettings set org.gnome.desktop.sound theme-name "Yaru"
echo "Done"
#
echo ""
echo -n "なにかキーを押してください:"
read -r -n 1 -s answer
echo ""
exit 0
