#!/bin/bash

  echo "=ファイラー nemo を消します="
  echo " ドックのお気に入りを調整"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp |  sed -e "s/'nemo.desktop',//g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"  
  #snap list contain firefox?

  echo " 実際にnemoを消去"
  sudo apt remove -y --purge nemo nemo
  sudo apt remove -y --autoremove 
  echo ""
  echo -n "なにかキーを押してください:"
  read -r -n 1 -s answer
  echo ""


