#!/bin/bash

  echo "=ファイラーthunarを消します ="
  echo " ドックのお気に入りからアイコンを消します"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp |  sed -e "s/'thunar.desktop',//g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"  
  echo " 実際に消去するコマンドが動きます"
  sudo apt remove -y --purge nemo "thunar*"
  sudo apt remove -y --autoremove >/dev/null 2>/dev/null
  sudo killall thunar
  rm -rf ~/.config/Thunar
  echo ""
  echo -n "なにかキーを押してください:"
  read -r -n 1 -s answer
  echo ""


