#!/bin/bash

# main
# remove all Moesound
echo " もえ音を消します。"
sudo rm -rf /usr/share/sounds/Moe*
# change sound gsetting
echo " 既定の音に設定を戻します。"
gsettings set org.gnome.desktop.sound theme-name "Yaru"
echo "終了"
#
echo ""
echo -n "キーを押してメニューに戻る:"
read -r -n 1 -s answer
echo ""
exit 0
