#!/bin/bash
  echo "=動画を見るソフトvlcをアンインストールします ="
  echo " 消すコマンドを動かします"
  sudo apt update >/dev/null 2>/dev/null
  sudo apt -y remove "vlc"
  echo ""
  echo -n "なにかキーを押してください:"
  read -r -n 1 -s answer
  echo ""


