#!/bin/bash
#Theme valiable
ThemeUrl=$1
ThemeFileName=`echo $ThemeUrl|awk -F"/" '{print $NF}'`
ThemeDirName=`echo $ThemeFileName|awk '{print substr($0,0,index($0,".")-1)}'`
ThemeName=$ThemeDirName
#login default valiable
LoginDefaultPngUrl=$2
LoginDefaultFileName=`echo $LoginDefaultPngUrl|awk -F"/" '{print $NF}'`

TempDir="Moebuntu.temp"

#Ask Yn
askyn() {
  echo -n "(Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo # just a final linefeed, optics...
  return $retval
}


loginlogobak() {
echo "=ログインロゴを既定に戻します(バックアップがある場合)="
if [ -e /usr/share/plymouth/ubuntu-logo.org.png ]; then
  sudo cp /usr/share/plymouth/ubuntu-logo.org.png /usr/share/plymouth/ubuntu-logo.png
echo "終了"
fi
}

removethemealtanatives() {
echo "=Moe GDM altanetivesのすべてを消去する="
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Green16/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-BlueGreen16/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Navy16/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Purple16/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Red16/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Orange16/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Yellow16/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Blue16/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Pink16/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
echo "終了"
}

# main
# make temp directory
if [ ! -d $TempDir ]; then
  mkdir $TempDir
fi
# Install curl
echo "=下準備でcurlというネットからのダウンロード用のコマンドをインストールする。="
dpkg -s curl >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt install -y curl
  else
      echo " すでにインストールされていました。"
fi

# Download Theme
echo " $ThemeFileNameをダウンロードします。"
curl -L $ThemeUrl --output "$TempDir/$ThemeFileName"

# Unpack
echo " $ThemeFileNameを展開します。"
tar Jxfv "$TempDir/$ThemeFileName" -C $TempDir > /dev/null 2> /dev/null

# set to themes Folder
echo " システムのテーマフォルダーにコピーします。"
cd $TempDir
sudo cp -R $ThemeDirName /usr/share/themes/
cd ..
echo "今システムにある萌えテーマ: `ls -d /usr/share/themes/Moe*`"
echo ""

# change theme gsetting
echo " システム変数をテーマに合わせます。"
gsettings set org.gnome.desktop.interface gtk-theme $ThemeName
gsettings set org.gnome.shell.extensions.user-theme name $ThemeName

# change login screen
echo -n "ログイン画面を変更しますか？"
if askyn; then
  echo " 下準備をします。"
  removethemealtanatives;
  loginlogobak;
  echo ""
  
# set update-altanatives
  echo " altanativesをテーマのログイン画面のために合わせます。"
  sudo update-alternatives --install /usr/share/gnome-shell/gdm-theme.gresource gdm-theme.gresource "/usr/share/themes/$ThemeDirName/gnome-shell/gnome-shell-theme.gresource" 20 >/dev/null 2>/dev/null
  sudo update-alternatives --set gdm-theme.gresource /usr/share/themes/$ThemeDirName/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  
# set login banner
  echo " ログインバナーを萌えにセットします。"
  sudo cp /usr/share/plymouth/ubuntu-logo.png /usr/share/plymouth/ubuntu-logo.org.png
  sudo cp /usr/share/themes/$ThemeDirName/ubuntu-logo.png /usr/share/plymouth/ubuntu-logo.png

# login png-file
  echo "Moebuntuの基本ログイン画面を使用する場合は「Y」を押してください。"
  echo " もしくは、自分のオリジナル画像（PNG形式）やサンプルイメージを使用する場合は「N」を押してください。:"
  if ! askyn; then    
    read -p "自分のオリジナルのログインイメージ（PNG形式）を使用する場合は、ファイラからそのイメージファイルをドラックアンドドロップしてください。何もせずにリターンボタンを押すとサンプルイメージが使用されます。:" FileDrop
    if [ "$FileDrop" = "" ]; then
# set default login picture
# download default login picture
      echo " サンプルイメージの使用を選択しました。" 
      echo -n " 四国めたんちゃん（東日本大震災からの復興キャラクター）の萌えイメージを使いますか?"
      if ! askyn; then
        # not apply
        echo " apply Moebuntu basic login picture"
        # remove temp-dir
        rm -rf $TempDir
        echo ""
        echo -n "Hit Any Key:"
        read -r -n 1 -s answer
        echo ""     
        exit 0        
      fi
      echo " ログイン画面をダウンロードしています。" 
      echo " $TempDir/$LoginDefaultFileNameをダウンロードします。"
      curl -L $LoginDefaultPngUrl --output "$TempDir/$LoginDefaultFileName"

# set default GDM
      echo " 四国めたんちゃんログイン画面をシステムに設定します。"
      sudo cp $TempDir/$LoginDefaultFileName /usr/share/themes/$ThemeDirName/gnome-shell/moebuntu_bg.png
    else

# FileDrop to login
      LoginFile=`echo $FileDrop | tr -d \'`
      echo "$LoginFileをログイン画面にします。 "
      if [ ! -e $LoginFile ]; then
        echo "ファイルがありません。"
        echo "ログイン画面を変えられません。"
        # remove temp-dir
        rm -rf $TempDir
        echo ""
        echo -n "キーを押してメニューに戻る:"
        read -r -n 1 -s answer
        echo ""     
        exit 0   
      fi
      sudo cp $LoginFile /usr/share/themes/$ThemeDirName/gnome-shell/moebuntu_bg.png
      echo "終了"
      echo ""
    fi
  else
    echo "ログイン画面を萌えにします。"
    echo "終了"
  fi
else  
  echo "ログイン画面を変更しません"
  echo "altanetivesが既定のYaruかをチェックします。"
  sudo update-alternatives --set gdm-theme.gresource /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  echo "終了"
  removethemealtanatives;
  loginlogobak;
fi
# remove temp-dir
rm -rf $TempDir
echo ""
echo -n "キーを押してメニューに戻る:"
read -r -n 1 -s answer
echo ""

