#!/bin/bash
# global variable
MoePlymouthURL="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/plymouth/mmspinner.tar.xz"
MoePlymouthFileName=`echo $MoePlymouthURL|awk -F"/" '{print $NF}'`
MoePlymouthDirName="mmspinner"
MoePlymouthBackGroundFile="/usr/share/plymouth/themes/mmspinner/background-tile.png"
PlymothThemePath="/usr/share/plymouth/themes"
MoeAlternativesPath="/usr/share/plymouth/themes/mmspinner/mmspinner.plymouth"
DetaultAlternativesPath="/usr/share/plymouth/themes/bgrt/bgrt.plymouth"
PlymouthDefaultPngUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/plymouth/plymouth-default.png"
PlymouthDefaultFileName=`echo $PlymouthDefaultPngUrl|awk -F"/" '{print $NF}'`
TempDir="Moebuntu.temp"

#Ask Yn
askyn() {
  echo -n "(Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo # just a final linefeed, optics...
  return $retval
}

removemoeplymouth() {
  echo " $MoePlymouthDirNameを消します。"
  if [ -d "$PlymothThemePath/$MoePlymouthDirName" ]; then
    sudo rm -rf "$PlymothThemePath/$MoePlymouthDirName"
  fi
}

removemoeplymouthalternaives() {
  echo " alternatives $MoeAlternativesPathを消します。"
  sudo update-alternatives --remove default.plymouth "$MoeAlternativesPath" >/dev/null 2>/dev/null
}

setdefaultplymouthalternatives() {
  echo " alternatives $DetaultAlternativesPathを設定します。"
  sudo update-alternatives --set default.plymouth "$DetaultAlternativesPath" >/dev/null 2>/dev/null
}

# Main
# Prepare for Moe-nized
echo "=起動画面を設定します="
#  Set-default-temporaly
echo " 下準備をします。"
setdefaultplymouthalternatives;
removemoeplymouthalternaives;
removemoeplymouth;

# Create temp dir
if [ ! -d $TempDir ]; then
  echo " $TempDirという一時フォルダーを作ります。"
  mkdir $TempDir
fi

# Install curl
echo " 下準備でcurlというネットからのダウンロード用のコマンドをインストールする。"
dpkg -s curl >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt install -y curl
  echo " 終了"
  else
      echo " すでにインストールされていました。"
fi

# Download Plymouth
echo " $MoePlymouthFileNameをダウンロードします。"
curl -L $MoePlymouthURL --output "$TempDir/$MoePlymouthFileName"

# Unpack
echo " $MoePlymouthFileNameを展開します。"
tar Jxfv "$TempDir/$MoePlymouthFileName" -C $TempDir > /dev/null 2> /dev/null

# Set to plymouth Folder
echo " システムのテーマフォルダにコピーします。"
cd $TempDir
sudo cp -R $MoePlymouthDirName "$PlymothThemePath/"
cd ..
echo " 今存在する起動画面はこれ: `ls -d "$PlymothThemePath/$MoePlymouthDirName"`"

# Set update-altanatives
  echo " 起動画面のaltanativeを設定します。"
  echo "  alternativeのdefault.plymouth項目に$MoeAlternativesPathをインストールします。"
  sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth "$MoeAlternativesPath" 20 >/dev/null 2>/dev/null
  echo "  altanativesのdefault.plymouth項目を$MoeAlternativesPathに切り替えます。"
  sudo update-alternatives --set default.plymouth "$MoeAlternativesPath" >/dev/null 2>/dev/null

# Change login screen
echo " Moebuntuの基本スクリーンイメージを使う場合「Y」を押してください。"
echo "　もしくは、自分のオリジナルのpng形式のイメージを入れる場合、また、例のイメージを入れる場合は「N」を押してください。"
if askyn; then
  # Moebuntu basic Change screen then not copy
  # Remove tempdir
  rm -rf $TempDir
  # Update-initramfs
  echo " initramfsをアップデートして、設定を反映させます。"
  echo " <しばらくお待ちください>"
  sudo update-initramfs -u -k all 
  echo "終了"
  echo -n "何かキーを押してメニューに戻る:"
  read -r -n 1 -s answer  
  echo ""
  exit 0
fi
# Choose Change Screen
read -p "自分のオリジナル（Png形式の）イメージを起動画面にしたい場合は、ファイラからドラックアンドドロップしてください。そのまま何も入れすにエンターキーを押すと例のイメージが設定されます。:" FileDrop
if [ "$FileDrop" = "" ]; then
  # Null return
  # Set to default
  echo " 例のイメージをダウンロードする。"
  curl -L $PlymouthDefaultPngUrl --output "$TempDir/$PlymouthDefaultFileName"
  # Set default plymouth picture
  echo " 例のイメージを起動画面として設定する。"
  sudo cp "$TempDir/$PlymouthDefaultFileName" $MoePlymouthBackGroundFile
  else
  # Drag-and-Drop string exists
  PlymouthFile=`echo $FileDrop | tr -d \'`
  if [ ! -e $PlymouthFile ]; then
    echo "指定した（ドラックアンドドロップした？）ファイルがありません。"
    echo "イメージを変えられませんでした。"
    # remove temp-dir
    rm -rf $TempDir
    # Update-initramfs
    echo " initramfsをアップデートして、設定を反映させます。"
    echo " <少しお待ちください>"
    sudo update-initramfs -u -k all 
    echo "終了"    
    echo -n "何かキーを押してメニューに戻る:"
    read -r -n 1 -s answer
    echo ""     
    exit 0   
  fi
  echo " 起動画面のイメージを$PlymouthFileに変えます。"
  sudo cp $PlymouthFile $MoePlymouthBackGroundFile
fi
# remove temp-dir
rm -rf $TempDir
# Update-initramfs
echo " initramfsをアップデートして、設定を反映させます。"
echo " <少しお待ちください>"
sudo update-initramfs -u -k all 
echo "終了"    
echo -n "何かキーを押してメニューに戻る:"
read -r -n 1 -s answer
echo ""     
exit 0
  








  

