#!/bin/bash
# global variable
MoePlymouthURL="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/plymouth/mmspinner.tar.xz"
MoePlymouthFileName=`echo $MoePlymouthURL|awk -F"/" '{print $NF}'`
MoePlymouthDirName="mmspinner"
MoePlymouthBackGroundFile="/usr/share/plymouth/themes/mmspinner/background-tile.png"
MoePlymouthBackGroungFileName=`echo $MoePlymouthBackGroundFile|awk -F"/" '{print $NF}'`
PlymothThemePath="/usr/share/plymouth/themes"
MoeAlternativesPath="/usr/share/plymouth/themes/mmspinner/mmspinner.plymouth"
DetaultAlternativesPath="/usr/share/plymouth/themes/bgrt/bgrt.plymouth"
PlymouthDefaultPngUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/plymouth/plymouth-default.png"
PlymouthDefaultFileName=`echo $PlymouthDefaultPngUrl|awk -F"/" '{print $NF}'`
TempDir="Moebuntu.temp"

#Ask Yn
askyn() {
  echo -n "(Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo # just a final linefeed, optics...
  return $retval
}

removemoeplymouth() {
  echo " $MoePlymouthDirName を消します"
  if [ -d "$PlymothThemePath/$MoePlymouthDirName" ]; then
    sudo rm -rf "$PlymothThemePath/$MoePlymouthDirName"
  fi
}

removemoeplymouthalternaives() {
  echo " alternatives $MoeAlternativesPath を消します"
  sudo update-alternatives --remove default.plymouth "$MoeAlternativesPath" >/dev/null 2>/dev/null
}

setdefaultplymouthalternatives() {
  echo " alternatives $DetaultAlternativesPath をセットします"
  sudo update-alternatives --set default.plymouth "$DetaultAlternativesPath" >/dev/null 2>/dev/null
}

# Main
# Prepare for Moe-nized
echo "=起動画面をセットします="
#  Set-default-temporaly
echo " かわいいにする用意をしています"
setdefaultplymouthalternatives;
removemoeplymouthalternaives;
removemoeplymouth;

# Create temp dir
if [ ! -d $TempDir ]; then
  echo " 一時的に使うフォルダ $TempDir を作ります"
  mkdir $TempDir
fi

# Install curl
echo " curl をインストールします"
dpkg -s curl >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt install -y curl
  echo " インストールしました"
  else
      echo " すでにインストールしてあります"
fi

# Install imagemagick-2212291856
echo " imagemagick インストールします"
dpkg -s imagemagick >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt install -y imagemagick
  else
      echo " すでにインストールされていました"
fi

# Download Plymouth
echo " $MoePlymouthFileName をダウンロードします"
curl -L $MoePlymouthURL --output "$TempDir/$MoePlymouthFileName"

# Unpack
echo " $MoePlymouthFileName を解凍します"
tar Jxfv "$TempDir/$MoePlymouthFileName" -C $TempDir > /dev/null 2> /dev/null

# Set to plymouth Folder
echo " システムテーマのフォルダーへコピーしています"
cd $TempDir
sudo cp -R $MoePlymouthDirName "$PlymothThemePath/"
cd ..
echo " 現在あるかわいい起動ファルダは次のとおりです: `ls -d "$PlymothThemePath/$MoePlymouthDirName"`"

# Set update-altanatives
  echo " 起動画面 altanative をセットします"
  echo "  alternative default.plymouth $MoeAlternativesPath を設定しています"
  sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth "$MoeAlternativesPath" 20 >/dev/null 2>/dev/null
  echo "  set altanatives default.plymouth $MoeAlternativesPath"
  sudo update-alternatives --set default.plymouth "$MoeAlternativesPath" >/dev/null 2>/dev/null

# Change login screen
echo " 萌えぶんちゅの基本の起動イメージで設定しますか（ハート柄）？ (この場合Yを押してください)"
# fix word for update 2212291928
echo -n "それとは違って、あなたの持っているオリジナルの絵や、例になるかわいい絵を入れますか？(この場合Nを押してください)?:"
if askyn; then
  # Moebuntu basic Change screen then not copy
  # Remove tempdir
  rm -rf $TempDir
  # Update-initramfs
  echo " update-initramfs"
  echo " <時間がかかります、お待ちください>"
  sudo update-initramfs -u -k all 
  echo "完了"
  echo -n "なにかキーを押してください:"
  read -r -n 1 -s answer  
  echo ""
  exit 0
fi
# Choose Change Screen
read -p "png形式などの画像を、ファイラーからドラックアンドドロップしてリターンキーを押してください。または、例のかわいい画像を使うなら、何も入れずにリターンキーを押してください。:" FileDrop
if [ "$FileDrop" = "" ]; then
  # Null return
  # Set to default
  echo " 例に上げるカワイイ画像を選択しました"
  echo "  継ぎ目のない繰り返しパターンのカワイイ絵でいいですね(Y/N):"
  if ! askyn; then
    #Not choose
    echo " 萌えぶんちゅの基本の画像を設定します。"
    # Remove tempdir
    rm -rf $TempDir
    # Update-initramfs
    echo " update-initramfs"
    echo " <少し時間がかかりますお待ちください>"
    sudo update-initramfs -u -k all 
    echo "完了"
    echo -n "なにかキーを押してください:"
    read -r -n 1 -s answer  
    echo ""
    exit 0
  fi
  echo " デフォルトの画像を読みこんでいます"
  curl -L $PlymouthDefaultPngUrl --output "$TempDir/$PlymouthDefaultFileName"
  # Set default plymouth picture
  echo " デフォルトの起動待ちの画像を設定しています"
  sudo cp "$TempDir/$PlymouthDefaultFileName" $MoePlymouthBackGroundFile
  else
  # Drag-and-Drop string exists
  PlymouthFile=`echo $FileDrop | tr -d \'`
  if [ ! -e $PlymouthFile ]; then
    echo "ご指定のファイルががありません!"
    echo "画像を変えることができませんでした"
    # remove temp-dir
    rm -rf $TempDir
    # Update-initramfs
    echo " update-initramfs"
    echo " <時間がかかりますので、お待ちください>"
    sudo update-initramfs -u -k all 
    echo "完了"    
    echo -n "なにかキーを押してください:"
    read -r -n 1 -s answer
    echo ""     
    exit 0   
  fi
  # file conversion-2212291856
  FileName=`echo $PlymouthFile|awk -F"/" '{print $NF}'`
  FileExtension=`echo ${FileName##*.}`
  echo "ファイルの拡張子は次のとおりです $FileExtension"
  if [ $FileExtension = "png" ] || [ $FileExtension = "PNG" ]; then  
    echo " 起動待ちのタイル状に並べられるファイルは次のものです $PlymouthFile"
    sudo cp "$PlymouthFile" $MoePlymouthBackGroundFile
    echo ""
  else
    echo " $PlymouthFile を $TempDir/$MoePlymouthBackGroungFileName に変換しています"
    ReturnValue=`convert "$PlymouthFile" $TempDir/$MoePlymouthBackGroungFileName`
    if [ "$ReturnValue" != "" ]; then
      echo "png形式の画像に変換できません"
      echo "起動待ち画面を変更できませんでした"
      # remove temp-dir
      rm -rf $TempDir
      echo ""
      echo -n "なにかキーを押してください:"
      read -r -n 1 -s answer
      echo ""     
      exit 0
    fi
    sudo cp $TempDir/$MoePlymouthBackGroungFileName $MoePlymouthBackGroundFile
    echo "完了"
    echo ""
  fi
fi
# remove temp-dir
rm -rf $TempDir
# Update-initramfs
echo " update-initramfs"
echo " <時間がかかりますので、お待ちください>"
sudo update-initramfs -u -k all 
echo "完了"    
echo -n "なにかキーを押してください:"
read -r -n 1 -s answer
echo ""     
exit 0
  








  

