#!/bin/bash
#Theme valiable
ThemeUrl=$1
ThemeFileName=`echo $ThemeUrl|awk -F"/" '{print $NF}'`
ThemeDirName=`echo $ThemeFileName|awk '{print substr($0,0,index($0,".")-1)}'`
ThemeName=$ThemeDirName
#login default valiable
LoginDefaultPngUrl=$2
LoginDefaultFileName=`echo $LoginDefaultPngUrl|awk -F"/" '{print $NF}'`

TempDir="Moebuntu.temp"

#Ask Yn
askyn() {
  echo -n "(Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo # just a final linefeed, optics...
  return $retval
}


loginlogobak() {
echo "=ログイン画面のロゴ（バナー）をデフォルトに変えます。(バックアップされているのであればですが）="
if [ -e /usr/share/plymouth/ubuntu-logo.org.png ]; then
  sudo cp /usr/share/plymouth/ubuntu-logo.org.png /usr/share/plymouth/ubuntu-logo.png
echo "完了"
fi
}

removethemealtanatives() {
echo "= すべての Moe GDM altanetives を消します。="
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Green17/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-BlueGreen17/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Navy17/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Purple17/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Red17/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Orange17/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Yellow17/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Blue17/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Pink17/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
echo "完了"
}

# main
# make temp directory
if [ ! -d $TempDir ]; then
  mkdir $TempDir
fi
# Install curl
echo " curlのインストール"
dpkg -s curl >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt install -y curl
  else
      echo " すでにインストールされていました"
fi

# Install imagemagick-2212291856
echo " imagemagickのインストール"
dpkg -s imagemagick >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt install -y imagemagick
  else
      echo " すでにインストールされていました"
fi

# Download Theme
echo " $ThemeFileName をダウンロードします"
curl -L $ThemeUrl --output "$TempDir/$ThemeFileName"

# Unpack
echo " $ThemeFileName を解凍します"
tar Jxfv "$TempDir/$ThemeFileName" -C $TempDir > /dev/null 2> /dev/null

# set to themes Folder
echo " copy to system theme folder"
cd $TempDir
sudo cp -R $ThemeDirName /usr/share/themes/
cd ..
echo "現在ある萌え(かわいい)テーマは次の通り: `ls -d /usr/share/themes/Moe*`"
echo ""

# change theme gsetting
echo " theme gsettings を変更します"
gsettings set org.gnome.desktop.interface gtk-theme $ThemeName
gsettings set org.gnome.shell.extensions.user-theme name $ThemeName

# change login screen
echo -n "ログイン画面を変更します"
if askyn; then
  echo " GDMとログインバナーの設定の用意=>"
  removethemealtanatives;
  loginlogobak;
  echo ""
  
# set update-altanatives
  echo " GDM update-altanatives を設定"
  sudo update-alternatives --install /usr/share/gnome-shell/gdm-theme.gresource gdm-theme.gresource "/usr/share/themes/$ThemeDirName/gnome-shell/gnome-shell-theme.gresource" 20 >/dev/null 2>/dev/null
  sudo update-alternatives --set gdm-theme.gresource /usr/share/themes/$ThemeDirName/gnome-shell/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  
# set login banner
  echo " ログインバナーを設定"
  sudo cp /usr/share/plymouth/ubuntu-logo.png /usr/share/plymouth/ubuntu-logo.org.png
  sudo cp /usr/share/themes/$ThemeDirName/ubuntu-logo.png /usr/share/plymouth/ubuntu-logo.png

# login png-file
  echo "萌えぶんちゅの基本画像を適用しますか？(Y)"
  # sentence modified at 2212291859
  echo -n " それとは違いあなたのオリジナルの画像や、例としてこちらで用意しているログイン画像を適用しますか？(この場合Nを押してください)?:"
  if ! askyn; then    
    read -p "png形式などのお好みの画像をファイラからドラックアンドドロップしてリターンキーを押してください。そのままリターンキーを押すと例となる画像が入ります。:" FileDrop
    if [ "$FileDrop" = "" ]; then
      # set default login picture
      # download default login picture
      echo " 例となる画像を設定します =" 
      echo " saki_12さんが描いたアニメの絵を例としていれますか?"
      if ! askyn; then
        # not apply
        echo " 萌えぶんちゅのの基本のログイン画像を適用します"
        # remove temp-dir
        rm -rf $TempDir
        echo ""
        echo -n "なにかキーを押してください:"
        read -r -n 1 -s answer
        echo ""     
        exit 0        
      fi
      echo " $TempDir/$LoginDefaultFileName をダウンロード"
      curl -L $LoginDefaultPngUrl --output "$TempDir/$LoginDefaultFileName"

# set default GDM
      echo " set ログインのデフォルト画像を GDM-theme に設定します"
      sudo cp $TempDir/$LoginDefaultFileName /usr/share/themes/$ThemeDirName/gnome-shell/moebuntu_bg.png
    else

# FileDrop to login
      LoginFile=`echo $FileDrop | tr -d \'`
      echo "=ドラックアンドドロップした $LoginFile をログイン画像として設定します="
      if [ ! -e $LoginFile ]; then
        echo "ファイルが見当たりません!"
        echo "ログイン画像を変える設定ができませんでした"
        # remove temp-dir
        rm -rf $TempDir
        echo ""
        echo -n "なにかキーを押してください:"
        read -r -n 1 -s answer
        echo ""     
        exit 0   
      fi
      # file conversion-2212291856
      FileName=`echo $LoginFile|awk -F"/" '{print $NF}'`
      FileExtension=`echo ${FileName##*.}`
      echo "ファイルの拡張子は $FileExtension です"
      if [ $FileExtension = "png" ] || [ $FileExtension = "PNG" ]; then  
        sudo cp "$LoginFile" /usr/share/themes/$ThemeDirName/gnome-shell/moebuntu_bg.png
        echo "完了"
        echo ""
      else
        echo " Convert $LoginFile to $TempDir/moebuntu_bg.png"
        ReturnValue=`convert "$LoginFile" $TempDir/moebuntu_bg.png`
        # echo " ReturnValue is $ReturnValue"
        if [ "$ReturnValue" != "" ]; then
          echo "PNG画像に変換できませんでした"
          echo "ログイン画像は変更設定できません"
          # remove temp-dir
          rm -rf $TempDir
          echo ""
          echo -n "なにかキーを押してください:"
          read -r -n 1 -s answer
          echo ""     
          exit 0
        fi
        sudo cp $TempDir/moebuntu_bg.png /usr/share/themes/$ThemeDirName/gnome-shell/moebuntu_bg.png
        echo "完了"
        echo ""
      fi
    fi
  else
    echo "=ログイン画像を萌え(カワイイ)化する="
    echo "完了"
  fi
else  
  echo "=ログイン画像を交換できませんでした="
  echo "デフォルトのYaruにできるようにaltanetivesをチェックします"
  sudo update-alternatives --set gdm-theme.gresource /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource >/dev/null 2>/dev/null
  echo "完了"
  removethemealtanatives;
  loginlogobak;
fi
# remove temp-dir
rm -rf $TempDir
echo ""
echo -n "なにかキーを押してください:"
read -r -n 1 -s answer
echo ""

