#!/bin/bash
TempDir="Moebuntu.temp"

SoundUrl=$1
SoundFileName=`echo $SoundUrl|awk -F"/" '{print $NF}'`
SoundDirName=`echo $SoundFileName|awk '{print substr($0,0,index($0,".")-1)}'`
SoundName=$SoundDirName

# echo $SoundUrl
# echo $SoundFileName
# echo $SoundDirName
# echo $SoundName

# main
# make temp directory
if [ ! -d $TempDir ]; then
  mkdir $TempDir
fi
# Install curl
echo " 下準備でcurlというネットからのダウンロード用のコマンドをインストールする。"
dpkg -s curl >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt install -y curl
  else
      echo " すでにインストールされていました。"
fi

# Download Sound
echo " $SoundFileNameをダウンロードします。"
curl -L $SoundUrl --output "$TempDir/$SoundFileName"

# Unpack
echo " $SoundFileNameを展開します。"
tar -xf "$TempDir/$SoundFileName" -C $TempDir > /dev/null 2> /dev/null

# set to themes Sound
echo " システムのサウンドフォルダにコピーします。"
cd $TempDir
sudo cp -R $SoundDirName /usr/share/sounds/
cd ..
echo "いまシステムに存在する萌サウンド: `ls -d /usr/share/sounds/Moe*`"
echo ""
# change sound gsetting
echo " $SoundNameにシステムにサウンドテーマを変更する。"
gsettings set org.gnome.desktop.sound theme-name $SoundName
# remove temp-dir
rm -rf $TempDir
echo ""
echo -n "キーを押してメニューに戻る:"
read -r -n 1 -s answer
echo ""
exit 0

