#!/bin/bash

asksure() {
  echo -n "本当にいいですか？ (Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo # just a final linefeed, optics...
  return $retval
}
removeallmoethemes() {
  echo "=すべてのここでの色のテーマを取り消す="
  if [ -d /usr/share/themes/Moe-Green17 ]; then
    sudo rm -rf /usr/share/themes/Moe-Green17
  fi
  if [ -d /usr/share/themes/Moe-BlueGreen17 ]; then
    sudo rm -rf /usr/share/themes/Moe-BlueGreen17
  fi  
  if [ -d /usr/share/themes/Moe-Navy17 ]; then
    sudo rm -rf /usr/share/themes/Moe-Navy17
  fi
  if [ -d /usr/share/themes/Moe-Purple17 ]; then
    sudo rm -rf /usr/share/themes/Moe-Purple17
  fi
  if [ -d /usr/share/themes/Moe-Red17 ]; then
    sudo rm -rf /usr/share/themes/Moe-Red17
  fi
  if [ -d /usr/share/themes/Moe-Orange17 ]; then
     sudo rm -rf /usr/share/themes/Moe-Orange17
  fi
  if [ -d /usr/share/themes/Moe-Yellow17 ]; then
    sudo rm -rf /usr/share/themes/Moe-Yellow17
  fi
  if [ -d /usr/share/themes/Moe-Blue17 ]; then
    sudo rm -rf /usr/share/themes/Moe-Blue17
  fi
  if [ -d /usr/share/themes/Moe-Pink17 ]; then
    sudo rm -rf /usr/share/themes/Moe-Pink17
  fi
  echo "完了"
}

removethemealtanatives() {
echo "=すべての萌え(カワイイ) GDM altanetives を取り消す="
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Green17/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-BlueGreen17/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Navy17/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Purple17/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Red17/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Orange17/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Yellow17/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Blue17/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Pink17/gnome-shell/gnome-shell-theme.gresource
echo "完了"
}

loginlogobak() {
echo "=ログインのロゴをデフォルトに変更します（もしバックアップされているのであればですが="
if [ -e /usr/share/plymouth/ubuntu-logo.org.png ]; then
  sudo cp /usr/share/plymouth/ubuntu-logo.org.png /usr/share/plymouth/ubuntu-logo.png
echo "完了"
fi
}

### main
echo "=テーマをデフォルトのYaruに設定する="
gsettings set org.gnome.desktop.interface gtk-theme "Yaru"
gsettings set org.gnome.shell.extensions.user-theme name "Yaru"
echo "完了"
# delete Moe-theme
echo ""
removeallmoethemes;
echo ""
# GDM theme to default
echo "=GDM Altanetive to デフォルトのYaruに設定する="
sudo update-alternatives --set gdm-theme.gresource /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource >/dev/null 2>/dev/null
echo "完了"
echo ""
removethemealtanatives;
echo ""
# login logo chane to default,if backuped
loginlogobak;
echo ""
echo -n "なにかキーを押してください:"
read -r -n 1 -s answer

