#!/bin/bash
#==== MoeIcon variable ====
MoeBasicWallUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/bg-basic.jpg"
MoeBasicWallFileName=`echo $MoeBasicWallUrl|awk -F"/" '{print $NF}'`
MoeWallUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/bg-default.jpg"
MoeWallFileName=`echo $MoeWallUrl|awk -F"/" '{print $NF}'`
SYSWallDir="/usr/share/backgrounds"
DefaultWallFileName="warty-final-ubuntu.png"
TempDir="Moebuntu.temp"
ConstMoeWallFileName="moe_wall.jpg"
ConstWallFileNameJpg="moe_wall.jpg"
ConstWallFileNamePng="moe_wall.png"

# Install curl
InstallCurl() {
  echo " curl をインストール"
  dpkg -s curl >/dev/null 2>&1
  if [ ! $? -eq 0 ]; then
    sudo apt -y install curl
    else
        echo "すでにインストールされていました"
  fi
  echo ""
}

# Install imagemagick-2212291856
InstallImagemagick() {
echo " imagemagick をインストール"
dpkg -s imagemagick >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt install -y imagemagick
  else
      echo " すでにインストールされていました"
fi
}

#Ask Yn
askyn() {
  echo -n "(Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo # just a final linefeed, optics...
  return $retval
}

# main
# make temp directory
if [ ! -d $TempDir ]; then
  echo " 一時利用するフォルダ $TempDir を作る"
  mkdir $TempDir
fi

# install or remove?
if [ "$1" = "install" ]; then
  # install
  echo "=デスクトップの背景を設定する="
  InstallCurl;
  InstallImagemagick;
  # Ask filename of wallpaper
  read -p "PNC形式の画像などをファイラからドラッグアンドドロップしてリターンしてください。何も入れすにリターンすると例としての画像が設定されます。:" FileDrop
  if [ "$FileDrop" = "" ]; then
# set default login picture
# download default login picture
    echo " 例としての画像を選択しました"
    echo "Toyによって描かれたアニメ調の可愛い画像を適用しますか？"
    if ! askyn; then
      echo " デクストップの背景を適用できませんでした"
      # remove temp-dir
      rm -rf $TempDir
      echo ""
      echo -n "なにかキーを押してください:"
      read -r -n 1 -s answer
      echo ""     
      exit 0 
    fi      
    echo " 例としての画像をダウンロードします=" 
    echo " download $MoeWallFileName をダウンロード"
    curl -L $MoeWallUrl --output "$TempDir/$MoeWallFileName"
    echo " $SYSWallDir にコピーします"
    sudo cp "$TempDir/$MoeWallFileName" "$SYSWallDir/$ConstMoeWallFileName"
    echo " $MoeWallFileName を設定します"
    gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$ConstMoeWallFileName"
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$ConstMoeWallFileName"
    echo "完了"
    echo " 一時的なフォルダ $TempDir を消します"
    rm -rf $TempDir
    echo ""
    echo -n "なにかキーを押してください:"
    read -r -n 1 -s answer
    echo ""
    exit 0 
  else
  # FileDrop to login
    WallFileFullPath=`echo $FileDrop | tr -d \'`
    echo "=ドロップされた $WallFileFullPath へデスクトップの背景としてセットします="
    if [ ! -e "$WallFileFullPath" ]; then
      echo "ファイルが存在しません!"
      echo "デスクトップの背景を変更できませんでした"
      # remove temp-dir
      rm -rf $TempDir
      echo ""
      echo -n "なにかキーを押してください:"
      read -r -n 1 -s answer
      echo ""     
      exit 0   
    fi
    echo " $WallFileFullPath を $SYSWallDir へコピーします"
    FileName=`echo $WallFileFullPath|awk -F"/" '{print $NF}'`
    FileExtension=`echo ${FileName##*.}`
    echo "拡張子は次のとおりです $FileExtension"
    if [ $FileExtension = "jpg" ] || [ $FileExtension = "JPG" ]; then
      ConstMoeWallFileName=$ConstWallFileNameJpg
    elif [ $FileExtension = "png" ] || [ $FileExtension = "PNG" ]; then
      ConstMoeWallFileName=$ConstWallFileNamePng
    else
      echo " 拡張子がjpgやpngでありません "
      echo " Pngへ変換します"
      # convert to png
      ConstMoeWallFileName=$ConstWallFileNamePng
      echo "ファイルの拡張子は次の通り $FileExtension"
      echo " $WallFileFullPath を $TempDir/$ConstMoeWallFileName へ変換します"
      ReturnValue=`convert "$WallFileFullPath" $TempDir/$ConstMoeWallFileName`
      if [ "$ReturnValue" != "" ]; then
        echo " Png画像に変換できませんでした"
        echo " デスクトップの背景は変えられませんでした"
        # remove temp-dir
        rm -rf $TempDir
        echo ""
        echo -n "なにかキーを押してください:"
        read -r -n 1 -s answer
        echo ""     
        exit 0
      fi
      sudo cp "$TempDir/$ConstMoeWallFileName" "$SYSWallDir/$ConstMoeWallFileName"
      echo "完了"
      echo " $TempDir/$ConstMoeWallFileName を $SYSWallDir/$ConstMoeWallFileName へコピーします"
      gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$ConstMoeWallFileName"
      gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$ConstMoeWallFileName"
      echo "完了"
      echo " 一時利用フォルダ $TempDir を消します"
      rm -rf $TempDir
      echo ""
      echo -n "なにかキーを押してください:"
      read -r -n 1 -s answer
      echo ""
      exit 0
    fi
    echo " $WallFileFullPath を $SYSWallDir へコピーします"
    sudo cp "$WallFileFullPath" "$SYSWallDir/$ConstMoeWallFileName"
    echo " $WallFileFullPath へ設定します"
    gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$ConstMoeWallFileName"
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$ConstMoeWallFileName"
    echo "完了"
    echo " 一時利用フォルダ $TempDir を消します"
     # remove temp-dir
    rm -rf $TempDir
    echo ""
    echo -n "なにかキーを押してください:"
    read -r -n 1 -s answer
    echo ""     
    exit 0 
  fi
  rm -rf $TempDir
  echo ""
  echo -n "なにかキーを押してください:"
  read -r -n 1 -s answer
  echo ""
  exit 0 
# remove
elif [ "$1" = "remove" ]; then
  echo "=萌え（カワイイ）デスクトップの背景 ${MoeWallFileName%.*} を消して、デフォルトのデスクトップの背景をセットします。="
  echo " $DefaultWallFileName を設定中"
  gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$DefaultWallFileName"
  gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$DefaultWallFileName"
  # if exsist remove MoeBuntuWall
  if [ -e "$SYSWallDir/$ConstWallFileNameJpg" ]; then
    echo " $SYSWallDir/$ConstWallFileNameJpg を消します"
    sudo rm "$SYSWallDir/$ConstWallFileNameJpg"
  fi
  if [ -e "$SYSWallDir/$ConstWallFileNamePng" ]; then
    echo " $SYSWallDir/$ConstWallFileNamePng を消します"
    sudo rm "$SYSWallDir/$ConstWallFileNamePng"
  fi
  echo "完了"
  echo ""
else
  echo "インストールなの? リムーブなの?"
fi
echo " 一時的なフォルダ $TempDir を消します"
rm -rf $TempDir
echo ""
echo -n "なにかキーを押してください:"
read -r -n 1 -s answer
echo ""

