#!/bin/bash
#==== MoeIcon variable ====
MoeBasicWallUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/bg-basic.jpg"
MoeBasicWallFileName=`echo $MoeBasicWallUrl|awk -F"/" '{print $NF}'`
MoeWallUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/22.04Lts/themes/bg-default.jpg"
MoeWallFileName=`echo $MoeWallUrl|awk -F"/" '{print $NF}'`
SYSWallDir="/usr/share/backgrounds"
DefaultWallFileName="warty-final-ubuntu.png"
TempDir="Moebuntu.temp"
ConstMoeWallFileName="moe_wall.jpg"

# Install curl
InstallCurl() {
  echo " 下準備でcurlというネットからのダウンロード用のコマンドをインストールする。"
  dpkg -s curl >/dev/null 2>&1
  if [ ! $? -eq 0 ]; then
    sudo apt -y install curl
    else
        echo "すでにインストールされていました。"
  fi
  echo ""
}
#Ask Yn
askyn() {
  echo -n "(Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo # just a final linefeed, optics...
  return $retval
}

# main
# make temp directory
if [ ! -d $TempDir ]; then
  echo " $TempDirという、一時フォルダを作ります"
  mkdir $TempDir
fi

# install or remove?
if [ "$1" = "install" ]; then
  # install
  echo "=$MoeWallFileNameをインストール="
  InstallCurl;
  echo " Toyさんの基本イメージを壁紙にするには「Y]を押してください。"
  echo " または、あなたのオリジナルの壁紙（JPG形式）を利用するか、例の壁紙を入れる場合には「N」を押してください：" 
  if askyn; then
    echo " $MoeBasicWallFileNameをダウンロードする。"
    curl -L $MoeBasicWallUrl --output "$TempDir/$MoeBasicWallFileName"
    echo " $TempDir/$MoeBasicWallFileNameから$SYSWallDir/$ConstMoeWallFileNameへコピーする。"
    sudo cp "$TempDir/$MoeBasicWallFileName" "$SYSWallDir/$ConstMoeWallFileName"
    echo " システムをfile://$SYSWallDir/$ConstMoeWallFileNameに設定する。"
    gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$ConstMoeWallFileName"
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$ConstMoeWallFileName" 
    echo " $TempDirという一時フォルダーを消します。"
    rm -rf $TempDir
    echo ""
    echo -n "何かキーを押してメニューに戻る:"
    read -r -n 1 -s answer
    echo ""
    exit 0     
  else
  # Ask filename of wallpaper
    read -p "設定するイメージファイル（JPG形式）をファイラからドラックアンドドロップしてください。そのまま何も入れずにリターンボタンを押した場合は例のイメージが使用されます。:" FileDrop
    if [ "$FileDrop" = "" ]; then
# set default login picture
# download default login picture
      echo " 例となるログインイメージをダウンロードします。" 
      echo " $MoeWallFileNameをダウンロードします。"
      curl -L $MoeWallUrl --output "$TempDir/$MoeWallFileName"
      echo " $SYSWallDirへコピーします"
      sudo cp "$TempDir/$MoeWallFileName" "$SYSWallDir/$ConstMoeWallFileName"
      echo " $MoeWallFileNameをシステムに設定します"
      gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$ConstMoeWallFileName"
      gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$ConstMoeWallFileName"
      echo "終了"
      echo " $TempDirという一時フォルダーを消します。"
      rm -rf $TempDir
      echo ""
      echo -n "何かキーを押してメニューに戻る:"
      read -r -n 1 -s answer
      echo ""
      exit 0 
    else
    # FileDrop to login
      WallFileFullPath=`echo $FileDrop | tr -d \'`
      echo "=ドロップされた $WallFileFullPathを壁紙に設定します。="
      if [ ! -e $WallFileFullPath ]; then
        echo "ファイルがありません!"
        echo "壁紙を変更できません。"
        # remove temp-dir
        rm -rf $TempDir
        echo ""
        echo -n "何かキーを押してメニューに戻る:"
        read -r -n 1 -s answer
        echo ""     
        exit 0   
      fi
      echo " $WallFileFullPathから$SYSWallDirへコピーする。"
      sudo cp "$WallFileFullPath" "$SYSWallDir/$ConstMoeWallFileName"
      echo " $WallFileFullPathをシステムに設定する。"
      gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$ConstMoeWallFileName"
      gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$ConstMoeWallFileName"
      echo "終了"
      echo " $TempDirという一時フォルダーを消します。"
      rm -rf $TempDir
      echo ""
      echo -n "キーを押してメニューに戻る:"
      read -r -n 1 -s answer
      echo ""
      exit 0 
    fi
  fi
  # remove
elif [ "$1" = "remove" ]; then
  echo "=$MoeWallFileNameを消して、既定に設定します。="
  echo " $DefaultWallFileNameにシステムをセットします。"
  gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$DefaultWallFileName"
  gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$DefaultWallFileName"
  # if exsist remove MoeBuntuWall
  if [ -e "$SYSWallDir/$ConstMoeWallFileName" ]; then
    echo " $SYSWallDir/$ConstMoeWallFileNameを消します。"
    sudo rm "$SYSWallDir/$ConstMoeWallFileName"
  fi
  echo "終了"
  echo ""
else
  echo "install? remove?"
fi
echo " $TempDirという一時フォルダーを消します。"
rm -rf $TempDir
echo ""
echo -n "キーを押してメニューに戻る:"
read -r -n 1 -s answer
echo ""

